openapi: 3.0.3
info:
  title: Non-Creating Methods Return 201
  version: 1.0.0
paths:
  /users/{userId}:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: getUser
      responses:
        "201":
          description: Created
    patch:
      operationId: patchUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "201":
          description: Created
    delete:
      operationId: deleteUser
      responses:
        "201":
          description: Created
